// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ActivateCompressor.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Drive.h"
#include "Commands/DriveStraight.h"
#include "Commands/Fire.h"
#include "Commands/ShooterSpeedUp.h"
#include "Commands/ShooterSpeedDown.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xboxController.reset(new Joystick(0));
    
    lS.reset(new JoystickButton(xboxController.get(), 9));
    lS->WhileHeld(new DriveStraight());
    rB.reset(new JoystickButton(xboxController.get(), 6));
    rB->WhileHeld(new Fire());
    lB.reset(new JoystickButton(xboxController.get(), 5));
    lB->WhileHeld(new ActivateCompressor());
    A.reset(new JoystickButton(xboxController.get(), 1));
    A->WhenPressed(new ShooterSpeedUp());
    B.reset(new JoystickButton(xboxController.get(), 2));
    B->WhenPressed(new ShooterSpeedDown());

    // SmartDashboard Buttons
    SmartDashboard::PutData("Drive Straight", new DriveStraight());
    SmartDashboard::PutData("Fire", new Fire());
    SmartDashboard::PutData("Activate Compressor", new ActivateCompressor());
    SmartDashboard::PutData("Drive", new Drive());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getxboxController() {
   return xboxController;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
